--- #YAML:1.0
name:                Crypt-X509
version:             0.40
abstract:            Parse a X.509 certificate
license:             ~
author:              
    - Mike Jackson, Alexander Jung, Duncan Segrest
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Convert::ASN1:                 0.19
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
